(define (square-list-recur items)
  (if (null? items)
      '()
      (cons (* (car items) (car items)) (square-list (cdr items)))))
(define (square-list-map items)
  (map (lambda (x) (* x x)) items))
