(define (make-account passwd balance)
  (let ((count-pass-error 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (call-the-cops)
      (error "FREEZE!!!"))
    (define (dispatch p m)
      (if (eq? passwd p) 
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACOUNT" m)))
          (begin (set! count-pass-error (+ 1 count-pass-error))
                 (if (> count-pass-error 3)
                     (call-the-cops)
                     (error "Incorrect password" count-pass-error)))))
    dispatch))

(define acc (make-account 'pass 100))
((acc 'p 'deposit) 100)
((acc 'pass 'deposit) 100)
((acc 'pass 'withdraw) 40)
